### ISSUE TITLE
Happened to stop by!

### ISSUE THREAD

**Issue by tanho63** [danabrey/dynastyprocess-php#1]
https://github.com/danabrey/dynastyprocess-php/blob/4ed1eacb75946ff5022c29ad84e5b04f6bca6378/src/Client.php#L13

Noticed that you were pointing at an older link here, not sure if GH might stop redirecting that at some point. New repo is at DynastyProcess/data (https://github.com/DynastyProcess/data/raw/master/files/db_playerids.csv etc) :)

**Comment by tanho63** [comment]
(Was looking for a GH-y spot to drop you feedback but can happily go over to your twitter :P )

**Comment by danabrey** [comment]
@tanho63 I only just saw this, haha

Fixed in https://github.com/danabrey/dynastyprocess-php/releases/tag/v1.6.1
